### ISSUE TITLE
辛苦sdk增加一下找回授权码接口实现

### ISSUE THREAD

**Issue by hub-chen** [yydzxz/ByteDanceOpen#10]
![image](https://user-images.githubusercontent.com/74441129/108978785-f326b580-76c4-11eb-8b41-b4aa24948c3b.png)

希望sdk增加找回授权码接口实现，不然一个月内不操作api接口调用的话就一定需要重新授权了。
https://microapp.bytedance.com/docs/zh-CN/mini-app/thirdparty/API/authorization/find

**Comment by yydzxz** [comment]
👌

**Comment by yydzxz** [comment]
新增接口在3.4.7版本已经发布 @hub-chen
