### ISSUE TITLE
获取小程序版本列表信息序列化错误

### ISSUE THREAD

**Issue by zerov1219** [yydzxz/ByteDanceOpen#15]
com.github.yydzxz.open.api.v1.response.code.CodeVersionsResponse.data.latest.screenshot字段在多张应用截图时接口返回的是List，出现序列化错误。
错误信息如下：
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: org.springframework.web.client.RestClientException: Error while extracting response for type [class com.github.yydzxz.open.api.v1.response.code.CodeVersionsResponse] and content type [application/json;charset=utf-8]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token
 at [Source: (PushbackInputStream); line: 1, column: 1871] (through reference chain: com.github.yydzxz.open.api.v1.response.code.CodeVersionsResponse["data"]->com.github.yydzxz.open.api.v1.response.code.CodeVersionsResponse$DataObj["latest"]->com.github.yydzxz.open.api.v1.response.code.CodeVersionsResponse$Latest["screenshot"])] with root cause

**Comment by yydzxz** [comment]
麻烦贴一下字节服务器返回的消息体

**Comment by yydzxz** [comment]
![image](https://user-images.githubusercontent.com/13087806/124711309-805dfe80-df30-11eb-9e4c-46df500bb078.png)
字节文档里这是个字符串,不过看你贴的错误,字节实际上可能返回的是个数组, 方便的话, 可以用日志中打印的请求url复制到postman执行一下,把详细的返回数据贴上来. 
我发布了一个4.0.3版本,把这个字段从`String`改为了`List<String>`, 你可以试试

**Comment by zerov1219** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    谢谢您的回件，非常抱歉，最近没有注意邮件，字节可能一张截图返回的是String，多张返回的是List<String>
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                ZeroV
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年7月7日 ***@***.***> 写道： 






字节文档里这是个字符串,不过看你贴的错误,字节实际上可能返回的是个数组

我发布了一个4.0.3版本,把这个字段从String改为了List<String>, 你可以试试



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by zerov1219** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    

    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    谢谢您的回件，非常抱歉，最近没有注意邮件，字节可能一张截图返回的是String，多张返回的是List<String>下面是一张截图的返回：{"data":{"audit":{"approvedApps":[],"attachInfo":{},"categories":["文体、旅游类-旅游-门票","文体、旅游类-旅游-旅游线路","文体、旅游类-旅游-旅游攻略","文体、旅游类-旅游-酒店服务","文体、旅游类-旅游-景区服务"],"ctime":1625740583,"developer_avatar":"http://sf1-ttcdn-tos.pstatp.com/img/mosaic-legacy/3791/5070639578~120x256.image","developer_id":"jonsen_liu","developer_name":"jonsen_liu","has_publish":0,"is_illegal_version":false,"reason":"","reason_detail":{},"status":0,"summary":"产品详情和用户中心底部加入资质证书查看功能（根据接口字段来显示）","version":"4.1.18"},"current":{"approvedApps":["今日头条","抖音","今日头条lite"],"attachInfo":{},"categories":["文体、旅游类-旅游-门票","文体、旅游类-旅游-旅游线路","文体、旅游类-旅游-旅游攻略","文体、旅游类-旅游-酒店服务","文体、旅游类-旅游-景区服务"],"ctime":1603854342,"developer_avatar":"http://sf1-ttcdn-tos.pstatp.com/img/mosaic-legacy/3791/5070639578~120x256.image","developer_id":"jonsen_liu","developer_name":"jonsen_liu","has_down":false,"notApprovedApps":[],"reason":"","reasonDetail":{},"rollback":{"can_rollback":false,"last_version":""},"summary":"整改","uid":2031493793724323,"version":"1.0.1"},"latest":{"categories":["文体、旅游类-旅游-门票","文体、旅游类-旅游-旅游线路","文体、旅游类-旅游-旅游攻略","文体、旅游类-旅游-酒店服务","文体、旅游类-旅游-景区服务"],"ctime":1625740577,"developer_avatar":"http://sf1-ttcdn-tos.pstatp.com/img/mosaic-legacy/3791/5070639578~120x256.image","developer_id":"jonsen_liu","developer_name":"jonsen_liu","has_audit":1,"screenshot":"","summary":"产品详情和用户中心底部加入资质证书查看功能（根据接口字段来显示）","version":"4.1.18"}},"errno":0,"message":"success"} 那个多张截图的昨天我当时看了是个List，所以可能要兼容两种情况哦
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                ZeroV
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年7月7日 ***@***.***> 写道： 






字节文档里这是个字符串,不过看你贴的错误,字节实际上可能返回的是个数组

我发布了一个4.0.3版本,把这个字段从String改为了List<String>, 你可以试试



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yydzxz** [comment]
感谢反馈, 在4.0.5版本已经兼容`String`和`List<String>`两种情况, 可以通过`parseScreenshot()`方法获取`screenshot`字段的值
