### ISSUE TITLE
错误异常：无限死循环

### ISSUE THREAD

**Issue by aouwuu** [yydzxz/ByteDanceOpen#22]
com.github.yydzxz.common.error.ByteDanceError#errorMessage

<img width="400" alt="image" src="https://user-images.githubusercontent.com/5414578/204484528-42afe91b-d1bb-40f0-ab10-54c695f5efb0.png">

**Comment by yydzxz** [comment]
好的,我看一下

**Comment by yydzxz** [comment]
4.1.1版本已经修复
