### ISSUE TITLE
xlog api

### ISSUE THREAD

**Issue by iamtorsten** [yydzxz/ByteDanceOpen#6]
Is it possible to decrypt and encrypt sdfp and xlog messages?

**Comment by yydzxz** [comment]
> Is it possible to decrypt and encrypt sdfp and xlog messages?

What does "sdfp" and "xlog" mean ?

**Comment by iamtorsten** [comment]
With this event they are sending device parameters Back to their servers and doing a trust score.

-------- Ursprüngliche Nachricht --------Von: yydzxz <notifications@github.com> Datum: 05.09.20  20:26  (GMT+01:00) An: yydzxz/ByteDanceOpen <ByteDanceOpen@noreply.github.com> Cc: Torsten Klinger <torsten.klinger@googlemail.com>, Author <author@noreply.github.com> Betreff: Re: [yydzxz/ByteDanceOpen] xlog api (#6) 

Is it possible to decrypt and encrypt sdfp and xlog messages?

What does "sdfp" and "xlog" mean ?

**Comment by yydzxz** [comment]
> With this event they are sending device parameters Back to their servers and doing a trust score.
> […](#)
> -------- Ursprüngliche Nachricht --------Von: yydzxz <notifications@github.com> Datum: 05.09.20 20:26 (GMT+01:00) An: yydzxz/ByteDanceOpen <ByteDanceOpen@noreply.github.com> Cc: Torsten Klinger <torsten.klinger@googlemail.com>, Author <author@noreply.github.com> Betreff: Re: [yydzxz/ByteDanceOpen] xlog api (#6) Is it possible to decrypt and encrypt sdfp and xlog messages? What does "sdfp" and "xlog" mean ? —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

sry, not support now
