### ISSUE TITLE
大佬好 在使用sdk时获取可选审核宿主段列表接口时返回值没有映射到

### ISSUE THREAD

**Issue by hub-chen** [yydzxz/ByteDanceOpen#8]
在调用v2提审代码接口时未获取到宿主列表导致字节接口抛出错误。字节接口实际是有返回数据的。

![image](https://user-images.githubusercontent.com/74441129/99389018-5dcf9480-2911-11eb-9c9a-cb95f6b7ce2c.png)
![image](https://user-images.githubusercontent.com/74441129/99389135-8b1c4280-2911-11eb-8059-aa53f3f3bad0.png)
**sdk对这个接口的映射是不是漏掉了data，导致映射不正确了。**
![image](https://user-images.githubusercontent.com/74441129/99389192-a12a0300-2911-11eb-9282-f5f525abca6a.png)
实际返回的结构是这样的如图：
![image](https://user-images.githubusercontent.com/74441129/99389294-ca4a9380-2911-11eb-89d0-cc21a1b20292.png)
麻烦尽快核实修复。多谢多谢

**Comment by yydzxz** [comment]
已经验证修复, 发布在3.3.2版本. 由于这是字节后来新增的接口,没有测试到, 非常抱歉.
然后sdk相关bug麻烦提到这个仓库 [ByteDanceOpen](https://github.com/yydzxz/ByteDanceOpen/issues), 谢谢
@hub-chen
