### ISSUE TITLE
authorizerRefreshToken为空，需要重新授权

### ISSUE THREAD

**Issue by hub-chen** [yydzxz/ByteDanceOpen#9]
麻烦大佬帮忙核实这个是否解决了噢
https://gitee.com/yydzxz/ByteDance-Open-Demo/issues/I2DQ3B#note_4111570

**Comment by yydzxz** [comment]
> 麻烦大佬帮忙核实这个是否解决了噢
> https://gitee.com/yydzxz/ByteDance-Open-Demo/issues/I2DQ3B#note_4111570

我这边目前没有复现这个问题，所以需要更详细信息，我在上面的链接中的回答里列了几条，可以看下能否提供

**Comment by hub-chen** [comment]
嗯呐 好的 我这边看看


------------------------------------------------------------------
发件人：yydzxz <notifications@github.com>
发送时间：2021年1月28日(星期四) 18:18
收件人：yydzxz/ByteDanceOpen <ByteDanceOpen@noreply.github.com>
抄　送：陈荣 <chenrong@zowoyoo.cn>; Author <author@noreply.github.com>
主　题：Re: [yydzxz/ByteDanceOpen] authorizerRefreshToken为空，需要重新授权 (#9)

麻烦大佬帮忙核实这个是否解决了噢
https://gitee.com/yydzxz/ByteDance-Open-Demo/issues/I2DQ3B#note_4111570
我这边目前没有复现这个问题，所以需要更详细信息，我在上面的链接中的回答里列了几条，可以看下能否提供

**Comment by hub-chen** [comment]
> > 麻烦大佬帮忙核实这个是否解决了噢
> > https://gitee.com/yydzxz/ByteDance-Open-Demo/issues/I2DQ3B#note_4111570
> 
> 我这边目前没有复现这个问题，所以需要更详细信息，我在上面的链接中的回答里列了几条，可以看下能否提供

大佬 新年好！ 我这边确实发现authorizerRefreshToken过了大概一个月后就不在缓存中了，没有看到有代码地方进行重新获取，可以辛苦帮忙再看看么  在授权期大概一个月内的是可以的，超过一个月的小程序授权就全部不行。

可以方便指出是在哪进行刷新authorizerRefreshToken，我在获取的地方没有看到有传参进行重新获取。

![image](https://user-images.githubusercontent.com/74441129/108592372-8c458b80-73a8-11eb-9038-b1f27562513c.png)

**Comment by hub-chen** [comment]
> > > 麻烦大佬帮忙核实这个是否解决了噢
> > > https://gitee.com/yydzxz/ByteDance-Open-Demo/issues/I2DQ3B#note_4111570
> > 
> > 
> > 我这边目前没有复现这个问题，所以需要更详细信息，我在上面的链接中的回答里列了几条，可以看下能否提供
> 
> 大佬 新年好！ 我这边确实发现authorizerRefreshToken过了大概一个月后就不在缓存中了，没有看到有代码地方进行重新获取，可以辛苦帮忙再看看么 在授权期大概一个月内的是可以的，超过一个月的小程序授权就全部不行。

**Comment by hub-chen** [comment]
1

**Comment by yydzxz** [comment]
> > > 麻烦大佬帮忙核实这个是否解决了噢
> > > https://gitee.com/yydzxz/ByteDance-Open-Demo/issues/I2DQ3B#note_4111570
> > 
> > 
> > 我这边目前没有复现这个问题，所以需要更详细信息，我在上面的链接中的回答里列了几条，可以看下能否提供
> 
> 大佬 新年好！ 我这边确实发现authorizerRefreshToken过了大概一个月后就不在缓存中了，没有看到有代码地方进行重新获取，可以辛苦帮忙再看看么 在授权期大概一个月内的是可以的，超过一个月的小程序授权就全部不行。
> 
> 可以方便指出是在哪进行刷新authorizerRefreshToken，我在获取的地方没有看到有传参进行重新获取。
> 
> ![image](https://user-images.githubusercontent.com/74441129/108592372-8c458b80-73a8-11eb-9038-b1f27562513c.png)

139-145行就是调用接口刷新authorizerRefreshToken
[相关接口文档](https://microapp.bytedance.com/docs/zh-CN/mini-app/thirdparty/API/authorization/update)

**Comment by yydzxz** [comment]
> > > > 麻烦大佬帮忙核实这个是否解决了噢
> > > > https://gitee.com/yydzxz/ByteDance-Open-Demo/issues/I2DQ3B#note_4111570
> > > 
> > > 
> > > 我这边目前没有复现这个问题，所以需要更详细信息，我在上面的链接中的回答里列了几条，可以看下能否提供
> > 
> > 
> > 大佬 新年好！ 我这边确实发现authorizerRefreshToken过了大概一个月后就不在缓存中了，没有看到有代码地方进行重新获取，可以辛苦帮忙再看看么 在授权期大概一个月内的是可以的，超过一个月的小程序授权就全部不行。

一个月当中，是不是小程序没有进行任何操作？

**Comment by hub-chen** [comment]
是的 任何操作都没有 这个可以确定





来自钉钉专属商务邮箱------------------------------------------------------------------
发件人：yydzxz<notifications@github.com>
日　期：2021年02月20日 22:38:04
收件人：yydzxz/ByteDanceOpen<ByteDanceOpen@noreply.github.com>
抄　送：hub-chen<chenrong@zowoyoo.cn>; State change<state_change@noreply.github.com>
主　题：Re: [yydzxz/ByteDanceOpen] authorizerRefreshToken为空，需要重新授权 (#9)

   
麻烦大佬帮忙核实这个是否解决了噢
https://gitee.com/yydzxz/ByteDance-Open-Demo/issues/I2DQ3B#note_4111570 
我这边目前没有复现这个问题，所以需要更详细信息，我在上面的链接中的回答里列了几条，可以看下能否提供 
大佬 新年好！ 我这边确实发现authorizerRefreshToken过了大概一个月后就不在缓存中了，没有看到有代码地方进行重新获取，可以辛苦帮忙再看看么 在授权期大概一个月内的是可以的，超过一个月的小程序授权就全部不行。  
一个月当中，是不是小程序没有进行任何操作？

**Comment by yydzxz** [comment]
> 是的 任何操作都没有 这个可以确定 来自钉钉专属商务邮箱------------------------------------------------------------------ 发件人：yydzxz<notifications@github.com> 日　期：2021年02月20日 22:38:04 收件人：yydzxz/ByteDanceOpen<ByteDanceOpen@noreply.github.com> 抄　送：hub-chen<chenrong@zowoyoo.cn>; State change<state_change@noreply.github.com> 主　题：Re: [yydzxz/ByteDanceOpen] authorizerRefreshToken为空，需要重新授权 (#9) 麻烦大佬帮忙核实这个是否解决了噢 https://gitee.com/yydzxz/ByteDance-Open-Demo/issues/I2DQ3B#note_4111570 我这边目前没有复现这个问题，所以需要更详细信息，我在上面的链接中的回答里列了几条，可以看下能否提供 大佬 新年好！ 我这边确实发现authorizerRefreshToken过了大概一个月后就不在缓存中了，没有看到有代码地方进行重新获取，可以辛苦帮忙再看看么 在授权期大概一个月内的是可以的，超过一个月的小程序授权就全部不行。 一个月当中，是不是小程序没有进行任何操作？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

> 是的 任何操作都没有 这个可以确定 来自钉钉专属商务邮箱------------------------------------------------------------------ 发件人：yydzxz<notifications@github.com> 日　期：2021年02月20日 22:38:04 收件人：yydzxz/ByteDanceOpen<ByteDanceOpen@noreply.github.com> 抄　送：hub-chen<chenrong@zowoyoo.cn>; State change<state_change@noreply.github.com> 主　题：Re: [yydzxz/ByteDanceOpen] authorizerRefreshToken为空，需要重新授权 (#9) 麻烦大佬帮忙核实这个是否解决了噢 https://gitee.com/yydzxz/ByteDance-Open-Demo/issues/I2DQ3B#note_4111570 我这边目前没有复现这个问题，所以需要更详细信息，我在上面的链接中的回答里列了几条，可以看下能否提供 大佬 新年好！ 我这边确实发现authorizerRefreshToken过了大概一个月后就不在缓存中了，没有看到有代码地方进行重新获取，可以辛苦帮忙再看看么 在授权期大概一个月内的是可以的，超过一个月的小程序授权就全部不行。 一个月当中，是不是小程序没有进行任何操作？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

没有操作的话，一个月authorizerRefreshToken过期就是正常的啊，只有进行了api调用，才会触发authorizerAccessToken和authorizerRefreshToken的刷新，如果不进行任何操作，一个月后authorizerRefreshToken就过期了，变成无效的了.一旦authorizerRefreshToken无效，就只能重新授权了。


authorizerAccessToken是调用api的凭证，字节是通过authorizerAccessToken来校验身份的，authorizerAccessToken的有效期很短，一般2个小时，一旦authorizerAccessToken过期，就会通过authorizerRefreshToken去获取新的authorizerAccessToken以及新的authorizerRefreshToken，所以，只有不断的调用小程序api，才能维持authorizerRefreshToken的不断更新。
如果一个月左右没有进行任何api调用，那么authorizerRefreshToken就自动过期了，必须重新授权才行，这个逻辑我们理解的一致吗？

**Comment by hub-chen** [comment]
> > 是的 任何操作都没有 这个可以确定 来自钉钉专属商务邮箱------------------------------------------------------------------ 发件人：yydzxz[notifications@github.com](mailto:notifications@github.com) 日　期：2021年02月20日 22:38:04 收件人：yydzxz/ByteDanceOpen[ByteDanceOpen@noreply.github.com](mailto:ByteDanceOpen@noreply.github.com) 抄　送：hub-chen[chenrong@zowoyoo.cn](mailto:chenrong@zowoyoo.cn); State change[state_change@noreply.github.com](mailto:state_change@noreply.github.com) 主　题：Re: [yydzxz/ByteDanceOpen] authorizerRefreshToken为空，需要重新授权 (#9) 麻烦大佬帮忙核实这个是否解决了噢 https://gitee.com/yydzxz/ByteDance-Open-Demo/issues/I2DQ3B#note_4111570 我这边目前没有复现这个问题，所以需要更详细信息，我在上面的链接中的回答里列了几条，可以看下能否提供 大佬 新年好！ 我这边确实发现authorizerRefreshToken过了大概一个月后就不在缓存中了，没有看到有代码地方进行重新获取，可以辛苦帮忙再看看么 在授权期大概一个月内的是可以的，超过一个月的小程序授权就全部不行。 一个月当中，是不是小程序没有进行任何操作？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> > 是的 任何操作都没有 这个可以确定 来自钉钉专属商务邮箱------------------------------------------------------------------ 发件人：yydzxz[notifications@github.com](mailto:notifications@github.com) 日　期：2021年02月20日 22:38:04 收件人：yydzxz/ByteDanceOpen[ByteDanceOpen@noreply.github.com](mailto:ByteDanceOpen@noreply.github.com) 抄　送：hub-chen[chenrong@zowoyoo.cn](mailto:chenrong@zowoyoo.cn); State change[state_change@noreply.github.com](mailto:state_change@noreply.github.com) 主　题：Re: [yydzxz/ByteDanceOpen] authorizerRefreshToken为空，需要重新授权 (#9) 麻烦大佬帮忙核实这个是否解决了噢 https://gitee.com/yydzxz/ByteDance-Open-Demo/issues/I2DQ3B#note_4111570 我这边目前没有复现这个问题，所以需要更详细信息，我在上面的链接中的回答里列了几条，可以看下能否提供 大佬 新年好！ 我这边确实发现authorizerRefreshToken过了大概一个月后就不在缓存中了，没有看到有代码地方进行重新获取，可以辛苦帮忙再看看么 在授权期大概一个月内的是可以的，超过一个月的小程序授权就全部不行。 一个月当中，是不是小程序没有进行任何操作？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 没有操作的话，一个月authorizerRefreshToken过期就是正常的啊，只有进行了api调用，才会触发authorizerAccessToken和authorizerRefreshToken的刷新，如果不进行任何操作，一个月后authorizerRefreshToken就过期了，变成无效的了.一旦authorizerRefreshToken无效，就只能重新授权了。
> 
> authorizerAccessToken是调用api的凭证，字节是通过authorizerAccessToken来校验身份的，authorizerAccessToken的有效期很短，一般2个小时，一旦authorizerAccessToken过期，就会通过authorizerRefreshToken去获取新的authorizerAccessToken以及新的authorizerRefreshToken，所以，只有不断的调用小程序api，才能维持authorizerRefreshToken的不断更新。
> 如果一个月左右没有进行任何api调用，那么authorizerRefreshToken就自动过期了，必须重新授权才行，这个逻辑我们理解的一致吗？

嗯 是的  这个是一样的 但是不是可以当快过期时进行重新获取么，不然不会有不断进行调用小程序的，除非我们写个服务去调用不操作。

**Comment by hub-chen** [comment]
> > 是的 任何操作都没有 这个可以确定 来自钉钉专属商务邮箱------------------------------------------------------------------ 发件人：yydzxz[notifications@github.com](mailto:notifications@github.com) 日　期：2021年02月20日 22:38:04 收件人：yydzxz/ByteDanceOpen[ByteDanceOpen@noreply.github.com](mailto:ByteDanceOpen@noreply.github.com) 抄　送：hub-chen[chenrong@zowoyoo.cn](mailto:chenrong@zowoyoo.cn); State change[state_change@noreply.github.com](mailto:state_change@noreply.github.com) 主　题：Re: [yydzxz/ByteDanceOpen] authorizerRefreshToken为空，需要重新授权 (#9) 麻烦大佬帮忙核实这个是否解决了噢 https://gitee.com/yydzxz/ByteDance-Open-Demo/issues/I2DQ3B#note_4111570 我这边目前没有复现这个问题，所以需要更详细信息，我在上面的链接中的回答里列了几条，可以看下能否提供 大佬 新年好！ 我这边确实发现authorizerRefreshToken过了大概一个月后就不在缓存中了，没有看到有代码地方进行重新获取，可以辛苦帮忙再看看么 在授权期大概一个月内的是可以的，超过一个月的小程序授权就全部不行。 一个月当中，是不是小程序没有进行任何操作？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> > 是的 任何操作都没有 这个可以确定 来自钉钉专属商务邮箱------------------------------------------------------------------ 发件人：yydzxz[notifications@github.com](mailto:notifications@github.com) 日　期：2021年02月20日 22:38:04 收件人：yydzxz/ByteDanceOpen[ByteDanceOpen@noreply.github.com](mailto:ByteDanceOpen@noreply.github.com) 抄　送：hub-chen[chenrong@zowoyoo.cn](mailto:chenrong@zowoyoo.cn); State change[state_change@noreply.github.com](mailto:state_change@noreply.github.com) 主　题：Re: [yydzxz/ByteDanceOpen] authorizerRefreshToken为空，需要重新授权 (#9) 麻烦大佬帮忙核实这个是否解决了噢 https://gitee.com/yydzxz/ByteDance-Open-Demo/issues/I2DQ3B#note_4111570 我这边目前没有复现这个问题，所以需要更详细信息，我在上面的链接中的回答里列了几条，可以看下能否提供 大佬 新年好！ 我这边确实发现authorizerRefreshToken过了大概一个月后就不在缓存中了，没有看到有代码地方进行重新获取，可以辛苦帮忙再看看么 在授权期大概一个月内的是可以的，超过一个月的小程序授权就全部不行。 一个月当中，是不是小程序没有进行任何操作？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 没有操作的话，一个月authorizerRefreshToken过期就是正常的啊，只有进行了api调用，才会触发authorizerAccessToken和authorizerRefreshToken的刷新，如果不进行任何操作，一个月后authorizerRefreshToken就过期了，变成无效的了.一旦authorizerRefreshToken无效，就只能重新授权了。
> 
> authorizerAccessToken是调用api的凭证，字节是通过authorizerAccessToken来校验身份的，authorizerAccessToken的有效期很短，一般2个小时，一旦authorizerAccessToken过期，就会通过authorizerRefreshToken去获取新的authorizerAccessToken以及新的authorizerRefreshToken，所以，只有不断的调用小程序api，才能维持authorizerRefreshToken的不断更新。
> 如果一个月左右没有进行任何api调用，那么authorizerRefreshToken就自动过期了，必须重新授权才行，这个逻辑我们理解的一致吗？

我看api文档意思在重新获取authorizerAccessToken（2h过期）的时候也会返回authorizerRefreshToken(一个月过期) 这样的话有没有可能做到不操作api调用的情况下在authorizerAccessToken快过期时重新获取呀。

**Comment by yydzxz** [comment]
> > > 是的 任何操作都没有 这个可以确定 来自钉钉专属商务邮箱------------------------------------------------------------------ 发件人：yydzxz[notifications@github.com](mailto:notifications@github.com) 日　期：2021年02月20日 22:38:04 收件人：yydzxz/ByteDanceOpen[ByteDanceOpen@noreply.github.com](mailto:ByteDanceOpen@noreply.github.com) 抄　送：hub-chen[chenrong@zowoyoo.cn](mailto:chenrong@zowoyoo.cn); State change[state_change@noreply.github.com](mailto:state_change@noreply.github.com) 主　题：Re: [yydzxz/ByteDanceOpen] authorizerRefreshToken为空，需要重新授权 (#9) 麻烦大佬帮忙核实这个是否解决了噢 https://gitee.com/yydzxz/ByteDance-Open-Demo/issues/I2DQ3B#note_4111570 我这边目前没有复现这个问题，所以需要更详细信息，我在上面的链接中的回答里列了几条，可以看下能否提供 大佬 新年好！ 我这边确实发现authorizerRefreshToken过了大概一个月后就不在缓存中了，没有看到有代码地方进行重新获取，可以辛苦帮忙再看看么 在授权期大概一个月内的是可以的，超过一个月的小程序授权就全部不行。 一个月当中，是不是小程序没有进行任何操作？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > > 是的 任何操作都没有 这个可以确定 来自钉钉专属商务邮箱------------------------------------------------------------------ 发件人：yydzxz[notifications@github.com](mailto:notifications@github.com) 日　期：2021年02月20日 22:38:04 收件人：yydzxz/ByteDanceOpen[ByteDanceOpen@noreply.github.com](mailto:ByteDanceOpen@noreply.github.com) 抄　送：hub-chen[chenrong@zowoyoo.cn](mailto:chenrong@zowoyoo.cn); State change[state_change@noreply.github.com](mailto:state_change@noreply.github.com) 主　题：Re: [yydzxz/ByteDanceOpen] authorizerRefreshToken为空，需要重新授权 (#9) 麻烦大佬帮忙核实这个是否解决了噢 https://gitee.com/yydzxz/ByteDance-Open-Demo/issues/I2DQ3B#note_4111570 我这边目前没有复现这个问题，所以需要更详细信息，我在上面的链接中的回答里列了几条，可以看下能否提供 大佬 新年好！ 我这边确实发现authorizerRefreshToken过了大概一个月后就不在缓存中了，没有看到有代码地方进行重新获取，可以辛苦帮忙再看看么 在授权期大概一个月内的是可以的，超过一个月的小程序授权就全部不行。 一个月当中，是不是小程序没有进行任何操作？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 没有操作的话，一个月authorizerRefreshToken过期就是正常的啊，只有进行了api调用，才会触发authorizerAccessToken和authorizerRefreshToken的刷新，如果不进行任何操作，一个月后authorizerRefreshToken就过期了，变成无效的了.一旦authorizerRefreshToken无效，就只能重新授权了。
> > authorizerAccessToken是调用api的凭证，字节是通过authorizerAccessToken来校验身份的，authorizerAccessToken的有效期很短，一般2个小时，一旦authorizerAccessToken过期，就会通过authorizerRefreshToken去获取新的authorizerAccessToken以及新的authorizerRefreshToken，所以，只有不断的调用小程序api，才能维持authorizerRefreshToken的不断更新。
> > 如果一个月左右没有进行任何api调用，那么authorizerRefreshToken就自动过期了，必须重新授权才行，这个逻辑我们理解的一致吗？
> 
> 我看api文档意思在重新获取authorizerAccessToken（2h过期）的时候也会返回authorizerRefreshToken(一个月过期) 这样的话有没有可能做到不操作api调用的情况下在authorizerAccessToken快过期时重新获取呀。

authorizerAccessToken和authorizerRefreshToken这两个东西，最重要的是authorizerRefreshToken。如果authorizerAccessToken过期了，使用过期的authorizerAccessToken调用字节的接口，字节会返回错误码40020
调用接口的重试逻辑是在这里，一旦捕获到错误，就会进行重试
![image](https://user-images.githubusercontent.com/13087806/108621140-d0e62b00-746b-11eb-924d-ad7aa5305233.png)

每次调用接口前，先回获取authorizerAccessToken，然后用authorizerAccessToken进行接口调用。如果这次接口调用时字节返回错误码40020了，那么sdk会让redis里我们自己存储的authorizerAccessToken过期掉，并且重新抛出异常，让外面知道这次调用出错了，自动进行重试。
![image](https://user-images.githubusercontent.com/13087806/108621056-50272f00-746b-11eb-969a-c6e688b5644c.png)
![image](https://user-images.githubusercontent.com/13087806/108621841-0db42100-7470-11eb-805c-17d4e5498ecb.png)

当重试进行第二次接口调用的时候，在获取authorizerAccessToken这一步，会判断本地redis是否有可用的authorizerAccessToken，由于上面40020错误码，导致本地authorizerAccessToken被清理，所以这里获取authorizerAccessToken的时候，会调用昨天说的那个接口，使用authorizerRefreshToken去获取新的authorizerAccessToken以及新的authorizerRefreshToken
![image](https://user-images.githubusercontent.com/13087806/108621721-43a4d580-746f-11eb-9742-8fe5f1f99818.png)
这里上面就是刷新authorizerAccessToken和authorizerRefreshToken的大致逻辑，你可以debug看下

所以重点就是，本地保存的authorizerAccessToken出了问题，会自动通过authorizerRefreshToken去刷新authorizerAccessToken和authorizerRefreshToken， 而authorizerRefreshToken出了问题（比如一个月没有任何操作自动过期），那只能重新授权

**Comment by hub-chen** [comment]
大佬 我看到文档中像有新家接口 可找回授权码再使用授权码换取小程序的接口调用凭证.

这个在刷新authorizerToken的代码哪可否麻烦添加一下呀。


------------------------------------------------------------------
发件人：yydzxz <notifications@github.com>
发送时间：2021年2月21日(星期日) 18:09
收件人：yydzxz/ByteDanceOpen <ByteDanceOpen@noreply.github.com>
抄　送：陈荣 <chenrong@zowoyoo.cn>; State change <state_change@noreply.github.com>
主　题：Re: [yydzxz/ByteDanceOpen] authorizerRefreshToken为空，需要重新授权 (#9)


是的 任何操作都没有 这个可以确定 来自钉钉专属商务邮箱------------------------------------------------------------------ 发件人：yydzxznotifications@github.com 日　期：2021年02月20日 22:38:04 收件人：yydzxz/ByteDanceOpenByteDanceOpen@noreply.github.com 抄　送：hub-chenchenrong@zowoyoo.cn; State changestate_change@noreply.github.com 主　题：Re: [yydzxz/ByteDanceOpen] authorizerRefreshToken为空，需要重新授权 (#9) 麻烦大佬帮忙核实这个是否解决了噢 https://gitee.com/yydzxz/ByteDance-Open-Demo/issues/I2DQ3B#note_4111570 我这边目前没有复现这个问题，所以需要更详细信息，我在上面的链接中的回答里列了几条，可以看下能否提供 大佬 新年好！ 我这边确实发现authorizerRefreshToken过了大概一个月后就不在缓存中了，没有看到有代码地方进行重新获取，可以辛苦帮忙再看看么 在授权期大概一个月内的是可以的，超过一个月的小程序授权就全部不行。 一个月当中，是不是小程序没有进行任何操作？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
是的 任何操作都没有 这个可以确定 来自钉钉专属商务邮箱------------------------------------------------------------------ 发件人：yydzxznotifications@github.com 日　期：2021年02月20日 22:38:04 收件人：yydzxz/ByteDanceOpenByteDanceOpen@noreply.github.com 抄　送：hub-chenchenrong@zowoyoo.cn; State changestate_change@noreply.github.com 主　题：Re: [yydzxz/ByteDanceOpen] authorizerRefreshToken为空，需要重新授权 (#9) 麻烦大佬帮忙核实这个是否解决了噢 https://gitee.com/yydzxz/ByteDance-Open-Demo/issues/I2DQ3B#note_4111570 我这边目前没有复现这个问题，所以需要更详细信息，我在上面的链接中的回答里列了几条，可以看下能否提供 大佬 新年好！ 我这边确实发现authorizerRefreshToken过了大概一个月后就不在缓存中了，没有看到有代码地方进行重新获取，可以辛苦帮忙再看看么 在授权期大概一个月内的是可以的，超过一个月的小程序授权就全部不行。 一个月当中，是不是小程序没有进行任何操作？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
没有操作的话，一个月authorizerRefreshToken过期就是正常的啊，只有进行了api调用，才会触发authorizerAccessToken和authorizerRefreshToken的刷新，如果不进行任何操作，一个月后authorizerRefreshToken就过期了，变成无效的了.一旦authorizerRefreshToken无效，就只能重新授权了。
 authorizerAccessToken是调用api的凭证，字节是通过authorizerAccessToken来校验身份的，authorizerAccessToken的有效期很短，一般2个小时，一旦authorizerAccessToken过期，就会通过authorizerRefreshToken去获取新的authorizerAccessToken以及新的authorizerRefreshToken，所以，只有不断的调用小程序api，才能维持authorizerRefreshToken的不断更新。
 如果一个月左右没有进行任何api调用，那么authorizerRefreshToken就自动过期了，必须重新授权才行，这个逻辑我们理解的一致吗？ 
我看api文档意思在重新获取authorizerAccessToken（2h过期）的时候也会返回authorizerRefreshToken(一个月过期) 这样的话有没有可能做到不操作api调用的情况下在authorizerAccessToken快过期时重新获取呀。
authorizerAccessToken和authorizerRefreshToken这两个东西，最重要的是authorizerRefreshToken。如果authorizerAccessToken过期了，使用过期的authorizerAccessToken调用字节的接口，字节会返回错误码40020
 调用接口的重试逻辑是在这里，一旦捕获到错误，就会进行重试
[image]
每次调用接口前，先回获取authorizerAccessToken，然后用authorizerAccessToken进行接口调用。如果这次接口调用时字节返回错误码40020了，那么sdk会让redis里我们自己存储的authorizerAccessToken过期掉，并且重新抛出异常，让外面知道这次调用出错了，自动进行重试。
[image]
当重试进行第二次接口调用的时候，在获取authorizerAccessToken这一步，会判断本地redis是否有可用的authorizerAccessToken，由于上面40020错误码，导致本地authorizerAccessToken被清理，所以这里获取authorizerAccessToken的时候，会调用昨天说的那个接口，使用authorizerRefreshToken去获取新的authorizerAccessToken以及新的authorizerRefreshToken
[image]
 这里上面就是刷新authorizerAccessToken和authorizerRefreshToken的大致逻辑，你可以debug看下
所以重点就是，本地保存的authorizerAccessToken出了问题，会自动通过authorizerRefreshToken去刷新authorizerAccessToken和authorizerRefreshToken， 而authorizerRefreshToken出了问题（比如一个月没有任何操作自动过期），那只能重新授权
